"""更新验证码表

Revision ID: 0099c12f0d6c
Revises: 53532f0e6921
Create Date: 2026-06-23 21:01:57.115742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0099c12f0d6c'
down_revision: Union[str, None] = '53532f0e6921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('ip_address', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_codes', 'ip_address')
    # ### end Alembic commands ###
