"""初始化

Revision ID: 53532f0e6921
Revises: 
Create Date: 2026-06-23 20:50:32.729455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53532f0e6921'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_operation', 'audit_logs', ['operation'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('idx_user_created', 'conversations', ['user_id', 'created_at'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limits'))
    )
    op.create_index('idx_rl_identifier_action', 'rate_limits', ['identifier', 'action_type'], unique=False)
    op.create_index('idx_rl_window', 'rate_limits', ['identifier', 'action_type', 'window_start'], unique=False)
    op.create_table('user_auth',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_auth')),
    sa.UniqueConstraint('email', name=op.f('uq_user_auth_email'))
    )
    op.create_index('idx_user_auth_email', 'user_auth', ['email'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('setting_key', sa.String(length=64), nullable=False),
    sa.Column('setting_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', 'setting_key', name='uq_user_settings_user_key')
    )
    op.create_index('idx_user_settings_user', 'user_settings', ['user_id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_codes'))
    )
    op.create_index('idx_vc_email_expires', 'verification_codes', ['email', 'expires_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('idx_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], name=op.f('fk_refresh_tokens_user_id_user_auth'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('idx_rt_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_rt_user_id', 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rt_user_id', table_name='refresh_tokens')
    op.drop_index('idx_rt_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_vc_email_expires', table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index('idx_user_settings_user', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('idx_user_auth_email', table_name='user_auth')
    op.drop_table('user_auth')
    op.drop_index('idx_rl_window', table_name='rate_limits')
    op.drop_index('idx_rl_identifier_action', table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index('idx_user_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_operation', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
